# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coder.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'coder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63oder.proto\x12\x05\x63oder\"\x8a\x01\n\x0b\x43odeRequest\x12\x14\n\x0csystemPrompt\x18\x01 \x01(\t\x12\x12\n\nuserPrompt\x18\x02 \x01(\t\x12\x18\n\x10workingDirectory\x18\x03 \x01(\t\x12\x13\n\x0b\x64ockerImage\x18\x04 \x01(\t\x12\x10\n\x08maxRetry\x18\x05 \x01(\x05\x12\x10\n\x08LLMModel\x18\x06 \x01(\t\"\x1c\n\x0c\x43odeResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2H\n\x0c\x43oderService\x12\x38\n\x0b\x45xecuteCode\x12\x12.coder.CodeRequest\x1a\x13.coder.CodeResponse0\x01\x42\rZ\x0b./protos/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013./protos/go'
  _globals['_CODEREQUEST']._serialized_start=23
  _globals['_CODEREQUEST']._serialized_end=161
  _globals['_CODERESPONSE']._serialized_start=163
  _globals['_CODERESPONSE']._serialized_end=191
  _globals['_CODERSERVICE']._serialized_start=193
  _globals['_CODERSERVICE']._serialized_end=265
# @@protoc_insertion_point(module_scope)
