# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0b\x63omputation\"\x1e\n\rStreamRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\x1e\n\x0eStreamResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2X\n\rStreamService\x12G\n\nStreamData\x12\x1a.computation.StreamRequest\x1a\x1b.computation.StreamResponse0\x01\x42\rZ\x0b./protos/gob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013./protos/go'
  _globals['_STREAMREQUEST']._serialized_start=30
  _globals['_STREAMREQUEST']._serialized_end=60
  _globals['_STREAMRESPONSE']._serialized_start=62
  _globals['_STREAMRESPONSE']._serialized_end=92
  _globals['_STREAMSERVICE']._serialized_start=94
  _globals['_STREAMSERVICE']._serialized_end=182
# @@protoc_insertion_point(module_scope)
