// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: protos/coder.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoderService_ExecuteCode_FullMethodName = "/coder.CoderService/ExecuteCode"
)

// CoderServiceClient is the client API for CoderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoderServiceClient interface {
	ExecuteCode(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CodeResponse], error)
}

type coderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoderServiceClient(cc grpc.ClientConnInterface) CoderServiceClient {
	return &coderServiceClient{cc}
}

func (c *coderServiceClient) ExecuteCode(ctx context.Context, in *CodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CodeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoderService_ServiceDesc.Streams[0], CoderService_ExecuteCode_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CodeRequest, CodeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoderService_ExecuteCodeClient = grpc.ServerStreamingClient[CodeResponse]

// CoderServiceServer is the server API for CoderService service.
// All implementations must embed UnimplementedCoderServiceServer
// for forward compatibility.
type CoderServiceServer interface {
	ExecuteCode(*CodeRequest, grpc.ServerStreamingServer[CodeResponse]) error
	mustEmbedUnimplementedCoderServiceServer()
}

// UnimplementedCoderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoderServiceServer struct{}

func (UnimplementedCoderServiceServer) ExecuteCode(*CodeRequest, grpc.ServerStreamingServer[CodeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteCode not implemented")
}
func (UnimplementedCoderServiceServer) mustEmbedUnimplementedCoderServiceServer() {}
func (UnimplementedCoderServiceServer) testEmbeddedByValue()                      {}

// UnsafeCoderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoderServiceServer will
// result in compilation errors.
type UnsafeCoderServiceServer interface {
	mustEmbedUnimplementedCoderServiceServer()
}

func RegisterCoderServiceServer(s grpc.ServiceRegistrar, srv CoderServiceServer) {
	// If the following call pancis, it indicates UnimplementedCoderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoderService_ServiceDesc, srv)
}

func _CoderService_ExecuteCode_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CodeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoderServiceServer).ExecuteCode(m, &grpc.GenericServerStream[CodeRequest, CodeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoderService_ExecuteCodeServer = grpc.ServerStreamingServer[CodeResponse]

// CoderService_ServiceDesc is the grpc.ServiceDesc for CoderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coder.CoderService",
	HandlerType: (*CoderServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteCode",
			Handler:       _CoderService_ExecuteCode_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/coder.proto",
}
